### PR TITLE
Modifications to support dash-daq R package development

### PR DESCRIPTION
**Pull request by rpkyle**
This PR proposes to make three changes in support of building in R package support for `dash-daq`:
- fix missing `locationSlider` entry and docstring in `Slider.propTypes` within `Slider.react.js`
- update `package.json` with additional metadata for R package `DESCRIPTION` file
- include JavaScript bundles in `dash_daq` (required by 'transpiler', will copy into R package `inst` subdirectory)

The initial R package has also been committed to this branch.

### CODE REVIEW

**Comment by shammamah** [comment]
@rpkyle Would you be able to add these changes into the CHANGELOG under the next version (0.1.5)?

**Comment by rpkyle** [comment]
> @rpkyle Would you be able to add these changes into the CHANGELOG under the next version (0.1.5)?

fixed in feb7b4ee47d4568e837307ef1692dea55b89c812

**Comment by rpkyle** [comment]
🎉  @shammamah mind giving me a dancing-themed emoji? 🙂

**Comment by shammamah** [comment]
💃

**Pull request merged**
